# -*- coding: utf-8 -*-
"""week2_numpy_visualization_OOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9SFThGkPB6fqaAQzX2_RiXQoF1wGi5o

# Week 2: NumPy, Vectorization & Data Visualization


<div dir="rtl">

## الأسبوع ده دسم لكن مهم جدا عشان بيتبني عليه في اللي جي ركز معايا و بالتوفيق إن شاء الله

## قسم المحتوى بشكل جيد على الأيام ..  وممكن تلاقي نفسك قدام بترجع للمحتوى ده لإنه أساسي في البرمجة اللي هنبني عليها بإذن الله فمفيش مشكلة إنك تفضل ترجع لهذه ال Notebook

</div>


Welcome to Week 2! Last week you learned Python fundamentals. This week you'll learn the **essential tools for machine learning**.

## What Happened Last Week?

✅ Variables & data types (int, float, str, bool)

✅ Lists and indexing

✅ Loops and iteration

✅ Functions

## What You'll Learn This Week

This week is **crucial** because everything you learn here will be used in every ML algorithm you implement!

```
┌────────────────────────────────────────────────────┐
│  Week 2 Tools and how we use them in ML            │
├────────────────────────────────────────────────────┤
│  NumPy Arrays     →  Feature matrices, weights     │
│  Vectorization    →  Fast gradient computations    │
│  Broadcasting     →  Batch operations              │
│  Matplotlib       →  Loss curves, visualizations   │
│  OOP Classes      →  Model implementations         │
└────────────────────────────────────────────────────┘
```

### Why This Matters

**Week 3**: You'll implement Linear Regression (Lecture 3)

**Every single algorithm** uses NumPy arrays, vectorization, and visualization!

**Estimated Time:** 5-6 hours



Let's begin! 🚀

<div dir="rtl">

## الأسبوع ٢: NumPy، التوجيه الشعاعي والتصور البياني

مرحباً بك في الأسبوع الثاني! في الأسبوع الماضي تعلمت أساسيات Python. هذا الأسبوع ستتقن **إن شاء الله الأدوات الأساسية للتعلم الآلي**.

</div>
"""

# Run this cell first!
import numpy as np
import matplotlib.pyplot as plt

# Set dark theme for visualizations
plt.style.use('dark_background')

print("✓ Libraries imported successfully!")
print(f"NumPy version: {np.__version__}")
print(f"Matplotlib version: {plt.matplotlib.__version__}")

"""---

## Part 1: Introduction to NumPy Arrays

### What is NumPy?

**NumPy** stands for "Numerical Python". It's a library (a collection of pre-written code) that makes Python great for numerical computing.

### The Problem with Python Lists

Last week you learned about Python lists: `[1, 2, 3, 4, 5]`

Lists are great, but they have problems for machine learning:

❌ **Slow** for mathematical operations

❌ **Can't do element-wise operations** easily

❌ **Not optimized** for numerical work

### The Solution: NumPy Arrays

NumPy arrays look similar to lists, but they're **supercharged** for ML:

✅ **10-100x faster** than Python lists

✅ **Built-in mathematical operations**

✅ **Perfect for matrices and vectors**

✅ **Used by ALL ML libraries** (TensorFlow, PyTorch, scikit-learn)

Let's see the difference:

<div dir="rtl">

## الجزء ١: مقدمة إلى مصفوفات NumPy

### ما هي NumPy؟

**NumPy** تعني "Python العددية". مكتبة (مجموعة من الأكواد المكتوبة مسبقاً) تجعل Python اسرع في العمليات على الاعداد .

</div>

"""

# Python list vs NumPy array
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python List:")
print(f"  Value: {python_list}")
print(f"  Type: {type(python_list)}")

print("\nNumPy Array:")
print(f"  Value: {numpy_array}")
print(f"  Type: {type(numpy_array)}")
print(f"  Data type inside: {numpy_array.dtype}")

# Why NumPy is better: Try multiplying by 2

# With Python list - doesn't do what we want!
python_list = [1, 2, 3]
result_list = python_list * 2
print(f"List * 2: {result_list}")  # Repeats the list!

# With NumPy array - does exactly what we want!
numpy_array = np.array([1, 2, 3])
result_array = numpy_array * 2
print(f"Array * 2: {result_array}")  # Multiplies each element!

"""### Creating NumPy Arrays

There are many ways to create NumPy arrays. Let's explore the most useful ones:

"""

# Method 1: From a Python list
arr1 = np.array([10, 20, 30, 40])
print(f"From list: {arr1}")

# Method 2: Array of zeros
arr2 = np.zeros(5)  # Creates [0, 0, 0, 0, 0]
print(f"Zeros: {arr2}")

# Method 3: Array of ones
arr3 = np.ones(4)  # Creates [1, 1, 1, 1]
print(f"Ones: {arr3}")

# Method 4: Range of values
arr4 = np.arange(0, 10, 2)  # Start at 0, stop before 10, step by 2
print(f"Range: {arr4}")

# Method 5: Evenly spaced values
arr5 = np.linspace(0, 1, 5)  # 5 values evenly spaced from 0 to 1
print(f"Linspace: {arr5}")

# ML Example: Initializing model weights

# Start with zeros (common in ML)
weights = np.zeros(4)
print(f"Initial weights: {weights}")

# Or small random values (also common)
np.random.seed(42)  # For reproducibility
weights = np.random.randn(4) * 0.01  # Small random values
print(f"Random weights: {weights}")
print(f"\nThese could be weights for a model with 4 features!")

"""### Array Shapes and Dimensions

**Understanding shapes is CRUCIAL for machine learning!**

Arrays can be:

- **1D** (vector): `[1, 2, 3, 4]` - shape `(4,)`
- **2D** (matrix): `[[1, 2], [3, 4]]` - shape `(2, 2)`
- **3D** (3d tensor): Used in images, videos

Visual representation:

```
1D Array (Vector):
[1, 2, 3, 4]  ← Single row
Shape: (4,)

2D Array (Matrix):
[[1, 2, 3],   ← Row 0
 [4, 5, 6]]   ← Row 1
Shape: (2, 3)  → 2 rows, 3 columns

3D Array (3d Tensor):
[[[1, 2],     ← Like multiple 2D matrices stacked
  [3, 4]],
 [[5, 6],
  [7, 8]]]
Shape: (2, 2, 2)
```

"""

# Different dimensional arrays

# 1D array (vector)
vector = np.array([1, 2, 3, 4])
print("1D Array (Vector):")
print(vector)
print(f"Shape: {vector.shape}")
print(f"Number of dimensions: {vector.ndim}")
print(f"Total elements: {vector.size}")
print()

# 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D Array (Matrix):")
print(matrix)
print(f"Shape: {matrix.shape}  ← (rows, columns)")
print(f"Number of dimensions: {matrix.ndim}")
print(f"Total elements: {matrix.size}")
print()

# ML Example: Dataset shape
# Each row is a person, columns are [height, weight, age]
data = np.array([
    [170, 68, 25],  # Person 0
    [165, 62, 30],  # Person 1
    [180, 75, 28],  # Person 2
    [175, 70, 35]   # Person 3
])

print("Dataset shape:", data.shape)
print(f"\nInterpretation:")
print(f"  - {data.shape[0]} samples (people)")
print(f"  - {data.shape[1]} features per sample")
print(f"\nData:\n{data}")

"""### Array Indexing and Slicing

Just like Python lists, but more powerful for 2D data!

"""

# 1D array indexing (same as lists)
arr = np.array([10, 20, 30, 40, 50])

print(f"Array: {arr}")
print(f"First element (index 0): {arr[0]}")
print(f"Last element (index -1): {arr[-1]}")
print(f"Slice [1:4]: {arr[1:4]}")

# 2D array indexing - THIS IS WHERE NUMPY SHINES!
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Data:")
print(data)
print()

# Access a single element: array[row, column]
print(f"Element at row 0, col 1: {data[0, 1]}")
print(f"Element at row 2, col 2: {data[2, 2]}")
print()

# Access entire row
print(f"Row 0: {data[0]}")
print(f"Row 1: {data[1]}")
print()

# Access entire column (THIS IS POWERFUL!)
print(f"Column 0 (all rows, col 0): {data[:, 0]}")
print(f"Column 2 (all rows, col 2): {data[:, 2]}")

# Visual explanation of slicing
print("Understanding data[:, 0]:")
print("")
print("data = [[10, 20, 30],    ← Row 0")
print("        [40, 50, 60],    ← Row 1")
print("        [70, 80, 90]]    ← Row 2")
print("         ↑")
print("         Column 0")
print("")
print("data[:, 0] means:")
print("  : = all rows")
print("  0 = column 0")
print(f"  Result: {data[:, 0]}")

# ML Example: Extracting features and labels
# Suppose we have: [feature1, feature2, feature3, label]
dataset = np.array([
    [1.5, 2.0, 3.0, 0],  # Sample 0
    [4.0, 5.0, 6.0, 1],  # Sample 1
    [7.0, 8.0, 9.0, 1],  # Sample 2
])

# Extract features (all columns except last)
X = dataset[:, :3]  # All rows, columns 0-2

# Extract labels (last column)
y = dataset[:, 3]   # All rows, column 3

print("Original dataset:")
print(dataset)
print(f"\nFeatures (X):\n{X}")
print(f"\nLabels (y): {y}")

"""### Now It's Your Turn! 🎯

Let's practice what you learned:

### Exercise 1.1: Creating Arrays (2 points)

Create NumPy arrays using different methods.
"""

# Create these NumPy arrays:
# - weights: array containing [0.5, 0.3, 0.8, 0.1]
# - zeros_array: array of 5 zeros
# - ones_array: array of 3 ones
# - range_array: array of [0, 2, 4, 6, 8] using np.arange

# YOUR CODE HERE
raise NotImplementedError()

print(f"Weights: {weights}")
print(f"Zeros: {zeros_array}")
print(f"Ones: {ones_array}")
print(f"Range: {range_array}")

# Tests for Exercise 1.1
assert isinstance(weights, np.ndarray), "weights should be a NumPy array"
assert np.array_equal(weights, np.array([0.5, 0.3, 0.8, 0.1])), "weights values incorrect"
assert len(zeros_array) == 5 and np.all(zeros_array == 0), "zeros_array incorrect"
assert len(ones_array) == 3 and np.all(ones_array == 1), "ones_array incorrect"
assert np.array_equal(range_array, np.array([0, 2, 4, 6, 8])), "range_array incorrect"
print("✓ Exercise 1.1 passed!")

"""### Exercise 1.2: Array Shapes (2 points)

Create a 2D array (matrix) representing a small dataset.

"""

# Create a 2D array called 'feature_matrix' with 4 samples and 3 features:
# Row 0: [1.0, 2.0, 3.0]
# Row 1: [4.0, 5.0, 6.0]
# Row 2: [7.0, 8.0, 9.0]
# Row 3: [10.0, 11.0, 12.0]
#
# Then extract:
# - num_samples: number of rows
# - num_features: number of columns

# YOUR CODE HERE
raise NotImplementedError()

print(f"Feature matrix:\n{feature_matrix}")
print(f"\nShape: {feature_matrix.shape}")
print(f"Samples: {num_samples}, Features: {num_features}")

# Tests for Exercise 1.2
assert feature_matrix.shape == (4, 3), "feature_matrix should be 4x3"
assert num_samples == 4, "num_samples should be 4"
assert num_features == 3, "num_features should be 3"
assert feature_matrix[0, 0] == 1.0, "First element should be 1.0"
assert feature_matrix[3, 2] == 12.0, "Last element should be 12.0"
print("✓ Exercise 1.2 passed!")

"""### Exercise 1.3: Array Indexing (3 points)

Practice extracting data from arrays.

"""

# Given this dataset (5 samples, 3 features):
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120],
    [130, 140, 150]
])

# Extract:
# - first_sample: the entire first row
# - last_column: all values from the last column (third feature)
# - middle_value: the value at row 2, column 1 (should be 80)
# - first_two_samples: rows 0 and 1 (all columns)

# YOUR CODE HERE
raise NotImplementedError()

print(f"First sample: {first_sample}")
print(f"Last column: {last_column}")
print(f"Middle value: {middle_value}")
print(f"First two samples:\n{first_two_samples}")

# Tests for Exercise 1.3
assert np.array_equal(first_sample, np.array([10, 20, 30])), "first_sample incorrect"
assert np.array_equal(last_column, np.array([30, 60, 90, 120, 150])), "last_column incorrect"
assert middle_value == 80, "middle_value should be 80"
assert first_two_samples.shape == (2, 3), "first_two_samples should be 2x3"
print("✓ Exercise 1.3 passed!")

"""---

## Part 2: Vectorization - The Secret to Fast ML Code

### What is Vectorization?

**Vectorization** means operating on entire arrays at once, instead of looping through elements one by one.

**Why does this matter?**

```
┌────────────────────────────────────────┐
│  Loop Approach (Slow)                  │
├────────────────────────────────────────┤
│  for i in range(len(arr)):             │
│      result[i] = arr[i] * 2            │
│                                        │
│  Speed: 100ms for 1M elements          │
└────────────────────────────────────────┘

┌────────────────────────────────────────┐
│  Vectorized Approach (Fast!)           │
├────────────────────────────────────────┤
│  result = arr * 2                      │
│                                        │
│  Speed: 1ms for 1M elements            │
│  → 100x FASTER!                        │
└────────────────────────────────────────┘
```

In machine learning, we often work with millions of data points. Vectorization is **essential** for practical ML!

### Where Vectorization is Used in ML (Check the Roadmap of our course: www.aibdaya.com)

**Lecture 3 (Linear Regression)**: Computing predictions for all samples

**Lecture 4 (Gradient Descent)**: Calculating gradients across entire dataset

**Lecture 5-6 (Neural Networks)**: Forward and backward propagation

**Lecture 7 (Preprocessing)**: Normalizing features for all samples

**Cluster 5 and 6**: Throughout different Deep learning models in NLP (Cluster 5) and Computer Vision (Cluster 6).


<div dir="rtl">

## الجزء ٢: التوجيه الشعاعي - سر الكود السريع للتعلم الآلي

### ما هو التوجيه الشعاعي؟

**التوجيه الشعاعي** يعني العمل على المصفوفات بأكملها مرة واحدة، بدلاً من المرور عبر العناصر واحداً تلو الآخر.

</div>

"""

# Let's see vectorization in action!

# Create test data
values = np.array([1, 2, 3, 4, 5])
print(f"Original: {values}")
print()

# Method 1: Using a loop (the slow way)
result_loop = []
for val in values:
    result_loop.append(val * 2)
result_loop = np.array(result_loop)

print("Loop approach:")
print(f"  Code: for val in values: result.append(val * 2)")
print(f"  Result: {result_loop}")
print(f"  Lines of code: 4")
print()

# Method 2: Vectorized (the fast way!)
result_vectorized = values * 2

print("Vectorized approach:")
print(f"  Code: values * 2")
print(f"  Result: {result_vectorized}")
print(f"  Lines of code: 1")
print()

print(f"Same result? {np.array_equal(result_loop, result_vectorized)}")
print("\nVectorized code is: Shorter ✓  Cleaner ✓  MUCH Faster ✓")

# Speed comparison with timing
import time

# Create larger array
large_array = np.arange(1000000)  # 1 million elements

# Time the loop approach
start = time.time()
result_loop = []
for val in large_array:
    result_loop.append(val * 2)
loop_time = time.time() - start

# Time the vectorized approach
start = time.time()
result_vec = large_array * 2
vec_time = time.time() - start

print("═" * 50)
print("SPEED COMPARISON (1 million elements)")
print("═" * 50)
print(f"Loop approach:       {loop_time:.4f} seconds")
print(f"Vectorized approach: {vec_time:.4f} seconds")
print(f"\nSpeedup: {loop_time/vec_time:.1f}x faster!")
print("═" * 50)

"""### Vectorized Operations

NumPy supports vectorized versions of all basic operations:

"""

# Basic arithmetic (all vectorized!)
arr = np.array([1, 2, 3, 4, 5]) # element wise ..

print(f"Original: {arr}")
print(f"Add 10: {arr + 10}")
print(f"Multiply by 2: {arr * 2}")
print(f"Square: {arr ** 2}")
print(f"Square root: {np.sqrt(arr)}")
print(f"Exponential: {np.exp(arr)}")

# Element-wise operations between arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a = {a}")
print(f"b = {b}")
print()
print(f"a + b = {a + b}")
print(f"a * b = {a * b}")
print(f"b / a = {b / a}")

# ML Example: Computing predictions
# Model: y = w1*x1 + w2*x2 + w3*x3 + bias

# We have 5 samples, 3 features each
X = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6],
    [5, 6, 7]
])

weights = np.array([0.5, 0.3, 0.2])
bias = 1.0

# Vectorized prediction!
predictions =  X @ weights + bias  # @ is matrix multiplication

print(f"Features:\n{X}")
print(f"\nWeights: {weights}")
print(f"Bias: {bias}")
print(f"\nPredictions: {predictions}")
print("\nAll 5 predictions computed in ONE line!")

"""### Broadcasting - NumPy's Superpower

**Broadcasting** is when NumPy automatically expands smaller arrays to match larger ones during operations.

This sounds complicated, but it's actually very intuitive!

```
Example: arr + 10

arr = [1, 2, 3, 4]
    +
10 → NumPy automatically broadcasts to [10, 10, 10, 10]
   =
    [11, 12, 13, 14]
```

**Used in ML for:**

- Feature normalization (Lecture 7)
- Adding bias terms (Lectures 3-6)
- Batch operations (All neural network lectures)

"""

# Broadcasting example 1: Scalar
arr = np.array([1, 2, 3, 4])
result = arr + 10  # 10 is broadcast to [10, 10, 10, 10]

print("Broadcasting a scalar:")
print(f"  {arr} + 10")
print(f"  = {result}")

# Broadcasting example 2: Row operation
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row = np.array([10, 20, 30])

result = matrix + row  # row is broadcast to each row of matrix

print("Broadcasting a row:")
print("Matrix:")
print(matrix)
print(f"\n+ Row: {row}")
print("\n= Result:")
print(result)

# Visual explanation
print("What happened:")
print("")
print("[[1, 2, 3],     [10, 20, 30]     [[11, 22, 33],")
print(" [4, 5, 6],  +  [10, 20, 30]  =   [14, 25, 36],")
print(" [7, 8, 9]]     [10, 20, 30]]     [17, 28, 39]]")
print("               ↑")
print("          Row broadcast to 3 rows")

# ML Example: Feature normalization (z-score)
# Formula: (x - mean) / std

# Dataset: 5 samples, 3 features
data = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
    [30, 300, 3000],
    [40, 400, 4000],
    [50, 500, 5000]
])

print("Original data:")
print(data)
print()

# Compute mean and std for each feature (column)
mean = np.mean(data, axis=0)  # axis=0 means "along rows" (compute for each column)
std = np.std(data, axis=0)

print(f"Mean per feature: {mean}")
print(f"Std per feature: {std}")
print()

# Normalize using broadcasting!
normalized = (data - mean) / std

print("Normalized data:")
print(normalized)
print()
print("Check: means should be ~0, stds should be ~1")
print(f"New means: {np.mean(normalized, axis=0)}")
print(f"New stds: {np.std(normalized, axis=0)}")

"""### Practice Time! 🎯

### Exercise 2.1: Basic Vectorized Operations (2 points)
"""

# Given:
features = np.array([10.0, 20.0, 30.0, 40.0])
weights = np.array([0.1, 0.2, 0.3, 0.4])

# Perform these vectorized operations:
# - squared_features: square each feature (features ** 2)
# - weighted_features: multiply features by weights element-wise
# - normalized_features: divide features by 10.0
# - sqrt_features: take square root of features

# YOUR CODE HERE
raise NotImplementedError()

print(f"Original: {features}")
print(f"Squared: {squared_features}")
print(f"Weighted: {weighted_features}")
print(f"Normalized: {normalized_features}")
print(f"Square root: {sqrt_features}")

# Tests for Exercise 2.1
assert np.array_equal(squared_features, np.array([100., 400., 900., 1600.])), "squared_features incorrect"
assert np.array_equal(weighted_features, np.array([1., 4., 9., 16.])), "weighted_features incorrect"
assert np.array_equal(normalized_features, np.array([1., 2., 3., 4.])), "normalized_features incorrect"
assert np.allclose(sqrt_features, np.array([3.162, 4.472, 5.477, 6.325]), atol=0.01), "sqrt_features incorrect"
print("✓ Exercise 2.1 passed!")

"""### Exercise 2.2: Broadcasting and Normalization (3 points)

Center the data by subtracting the mean from each column.

"""

# Given this feature matrix (3 samples, 4 features):
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Calculate the mean of each column (use axis=0)
# Then subtract the mean from each column to center the data
# Store the result in 'X_centered'
#
# Hint: Use np.mean with axis=0 to get column means
# Then use broadcasting to subtract

# YOUR CODE HERE
raise NotImplementedError()

print(f"Original X:\n{X}")
print(f"\nFeature means: {feature_means}")
print(f"\nCentered X:\n{X_centered}")
print(f"\nNew means (should be ~0): {np.mean(X_centered, axis=0)}")

# Tests for Exercise 2.2
assert X_centered.shape == (3, 4), "X_centered shape incorrect"
assert np.allclose(np.mean(X_centered, axis=0), 0, atol=1e-10), "Column means should be 0"
expected_first_row = np.array([-4, -4, -4, -4])
assert np.allclose(X_centered[0], expected_first_row), "First row incorrect"
print("✓ Exercise 2.2 passed!")

"""### Exercise 2.3: Dot Product and Predictions (3 points)

The dot product is THE most important operation in ML!

Used in: Linear Regression, Logistic Regression, Neural Networks, Transformers, ALL models!

"""

# Given:
# - features: a single data point with 4 features
# - weights: model weights for each feature
# - bias: model bias term

features = np.array([1.5, 2.0, 0.5, 3.0])
weights = np.array([0.2, 0.3, 0.1, 0.4])
bias = 0.5

# Calculate the prediction using the formula:
# prediction = (features · weights) + bias
#
# Use np.dot() or @ operator for the dot product
# Store in 'prediction'

# YOUR CODE HERE
raise NotImplementedError()

print(f"Features: {features}")
print(f"Weights: {weights}")
print(f"Bias: {bias}")
print(f"\nPrediction: {prediction:.4f}")
print(f"\nThis is how Linear Regression makes predictions!")

# Tests for Exercise 2.3
# Manual: 1.5*0.2 + 2.0*0.3 + 0.5*0.1 + 3.0*0.4 + 0.5 = 0.3 + 0.6 + 0.05 + 1.2 + 0.5 = 2.65
assert abs(prediction - 2.65) < 0.01, f"prediction should be 2.65, got {prediction}"
print("✓ Exercise 2.3 passed!")

"""---

## Part 3: Statistical Operations for ML

### Why Statistics Matter in ML

You'll use these operations **constantly**:

- **Data preprocessing** (Lecture 7): Normalize features
- **Model evaluation** (Lectures 4-10): Calculate loss, accuracy
- **Understanding data** (All lectures): Mean, variance, distribution
- **Gradient descent** (Lecture 4): Compute gradients

### Common Statistical Functions

"""

# Sample data: test scores
scores = np.array([85, 90, 78, 92, 88, 95, 82, 89, 91, 87])

print(f"Scores: {scores}")
print()
print(f"Mean (average): {np.mean(scores):.2f}")
print(f"Median (middle value): {np.median(scores):.2f}")
print(f"Standard deviation: {np.std(scores):.2f}")
print(f"Variance: {np.var(scores):.2f}")
print(f"Min: {np.min(scores)}")
print(f"Max: {np.max(scores)}")
print(f"Sum: {np.sum(scores)}")

# Working with 2D arrays (axis parameter)

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Data:")
print(data)
print()

# axis=0 means "along rows" (compute for each column)
print(f"Mean of each column (axis=0): {np.mean(data, axis=0)}")

# axis=1 means "along columns" (compute for each row)
print(f"Mean of each row (axis=1): {np.mean(data, axis=1)}")

# No axis means "entire array"
print(f"Mean of entire array: {np.mean(data):.2f}")

# Visual explanation of axis
print("Understanding axis:")
print("")
print("data = [[10, 20, 30],")
print("        [40, 50, 60],")
print("        [70, 80, 90]]")
print("")
print("axis=0 (down the rows, for each column):")
print("  Column 0: mean([10, 40, 70]) = 40")
print("  Column 1: mean([20, 50, 80]) = 50")
print("  Column 2: mean([30, 60, 90]) = 60")
print("  Result: [40, 50, 60]")
print("")
print("axis=1 (across the columns, for each row):")
print("  Row 0: mean([10, 20, 30]) = 20")
print("  Row 1: mean([40, 50, 60]) = 50")
print("  Row 2: mean([70, 80, 90]) = 80")
print("  Result: [20, 50, 80]")

"""### Normalization Techniques

Normalization is essential in ML (Lecture 7). Let's learn the two most common methods:

"""

# Technique 1: Min-Max Normalization
# Formula: (x - min) / (max - min)
# Result: Values in range [0, 1] .. we reference to the min first and then
# divide by the whole range so the values will be always between 0 and 1

data = np.array([10, 20, 30, 40, 50])

min_val = np.min(data)
max_val = np.max(data)
normalized = (data - min_val) / (max_val - min_val)

print("Min-Max Normalization:")
print(f"  Original: {data}")
print(f"  Min: {min_val}, Max: {max_val}")
print(f"  Normalized: {normalized}")
print(f"  Range: [{np.min(normalized)}, {np.max(normalized)}]")

# Technique 2: Z-Score Normalization (Standardization)
# Formula: (x - mean) / std
# Result: Mean = 0, Std = 1

data = np.array([10, 20, 30, 40, 50])

mean = np.mean(data)
std = np.std(data)
standardized = (data - mean) / std

print("Z-Score Normalization:")
print(f"  Original: {data}")
print(f"  Mean: {mean}, Std: {std:.2f}")
print(f"  Standardized: {standardized}")
print(f"  New mean: {np.mean(standardized):.10f}")
print(f"  New std: {np.std(standardized):.10f}")

"""### Practice Time! 🎯

### Exercise 3.1: Z-Score Normalization Function (3 points)

Implement z-score normalization - one of the most common preprocessing steps!
"""

def z_score_normalize(data):
    """
    Normalize data using z-score (standardization).

    Formula: (x - mean) / std

    Args:
        data: NumPy array of values

    Returns:
        Normalized array with mean≈0 and std≈1
    """
    # YOUR CODE HERE
    raise NotImplementedError()


# Test your function
test_data = np.array([10, 20, 30, 40, 50])
normalized = z_score_normalize(test_data)

print(f"Original: {test_data}")
print(f"Normalized: {normalized}")
print(f"New mean: {np.mean(normalized):.10f}")
print(f"New std: {np.std(normalized):.10f}")

# Tests for Exercise 3.1
result = z_score_normalize(np.array([10, 20, 30, 40, 50]))
assert np.allclose(np.mean(result), 0, atol=1e-10), "Mean should be 0"
assert np.allclose(np.std(result), 1, atol=1e-10), "Std should be 1"

result2 = z_score_normalize(np.array([1, 2, 3, 4, 5]))
assert len(result2) == 5, "Output length incorrect"
print("✓ Exercise 3.1 passed!")

"""### Exercise 3.2: Mean Squared Error (MSE) (3 points)

MSE is one of the most common loss functions in regression (Lecture 3)!

"""

def mean_squared_error(y_true, y_pred):
    """
    Calculate Mean Squared Error.

    Formula: MSE = mean((y_true - y_pred)²)

    Args:
        y_true: True values (NumPy array)
        y_pred: Predicted values (NumPy array)

    Returns:
        MSE as a float
    """
    # YOUR CODE HERE
    raise NotImplementedError()


# Test your function
true_values = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
predictions = np.array([1.1, 2.2, 2.9, 4.3, 4.8])
mse = mean_squared_error(true_values, predictions)

print(f"True values: {true_values}")
print(f"Predictions: {predictions}")
print(f"MSE: {mse:.4f}")

# Tests for Exercise 3.2
mse1 = mean_squared_error(np.array([1, 2, 3]), np.array([1, 2, 3]))
assert abs(mse1 - 0) < 0.01, "MSE of perfect predictions should be 0"

mse2 = mean_squared_error(np.array([0, 0, 0]), np.array([1, 1, 1]))
assert abs(mse2 - 1.0) < 0.01, "MSE incorrect"

mse3 = mean_squared_error(np.array([1, 2, 3, 4]), np.array([2, 3, 4, 5]))
assert abs(mse3 - 1.0) < 0.01, "MSE incorrect"

print("✓ Exercise 3.2 passed!")

"""### Exercise 3.3: Min-Max Normalization Function (2 points)

"""

def min_max_normalize(data):
    """
    Normalize to [0,1] range using min-max scaling.

    Formula: (x - min) / (max - min)

    Args:
        data: NumPy array

    Returns:
        Normalized array with values in [0, 1]
    """
    # YOUR CODE HERE
    raise NotImplementedError()


# Test
data = np.array([10, 20, 30, 40, 50])
result = min_max_normalize(data)
print(f"Original: {data}")
print(f"Normalized: {result}")

# Tests for Exercise 3.3
r = min_max_normalize(np.array([0, 50, 100]))
assert abs(r[0]-0.0) < 0.01 and abs(r[1]-0.5) < 0.01 and abs(r[2]-1.0) < 0.01, "Normalization incorrect"

r2 = min_max_normalize(np.array([10, 20, 30]))
assert abs(np.min(r2) - 0.0) < 0.01 and abs(np.max(r2) - 1.0) < 0.01, "Range incorrect"
print("✓ Exercise 3.3 passed!")

"""---

## Part 4: Data Visualization with Matplotlib

### Why Visualization Matters

**In Machine Learning, visualization is NOT optional - it's essential!**

You'll use plots to:

- **Understand your data** (Lectures 7-10): Feature distributions, outliers

- **Debug models** (All lectures): Training curves, loss trends

- **Communicate results** (All projects): Show model performance

- **Make decisions** (Lectures 7-10): Choose hyperparameters, detect overfitting

### Matplotlib Basics

**Matplotlib** is THE standard plotting library for Python. Every ML practitioner uses it!

<div dir="rtl">

## الجزء ٤: التصور البياني للبيانات باستخدام Matplotlib

### لماذا التصور البياني مهم؟

**في ال Machine Learning، التصور البياني مش اختياري - بل ضروري!**

هانستخدم الرسوم البيانية عشان:

- **فهم بياناتك** (المحاضرات ٧-١٠): توزيعات الخصائص، القيم الشاذة
- **تصحيح أخطاء النماذج** (جميع المحاضرات): منحنيات التدريب، اتجاهات الخسارة

</div>

"""

# Verify matplotlib is ready
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('dark_background')
print("✓ Matplotlib ready!")

"""### Basic Line Plot

The simplest plot - perfect for showing trends over time.

"""

# Simple line plot
x = np.linspace(0, 10, 1000)  # 100 points from 0 to 10

y = np.sin(x)
# I want you to focus on the example figure and how to plot it
# and don't worry about the function (sine wave) used

plt.figure(figsize=(10, 6)) # plt.figure(figsize=(19.2, 10.8), dpi=200)
plt.plot(x, y)
plt.title('Sine Wave', fontsize=16)
plt.xlabel('X values', fontsize=12)
plt.ylabel('Y values', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()
print("This is how you create a basic plot!")

# ML Example: Training Loss Curve
# Simulating loss decreasing over epochs

epochs = np.arange(1, 51)  # 50 epochs
loss = 2.0 * np.exp(-0.1 * epochs) + 0.1  # Exponential decay

plt.figure(figsize=(10, 6))
plt.plot(epochs, loss, linewidth=2, color='cyan')
plt.title('Training Loss Over Time', fontsize=16, fontweight='bold')
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

print("This is a typical ML training curve!")
print("You'll see this in Lectures 3-6 (Linear Regression, Gradient Descent, Neural Networks)")

"""### Scatter Plots

Perfect for visualizing 2D data and classification problems.

"""

# Basic scatter plot
np.random.seed(42)
x = np.random.randn(50) # Sampling 50 points randomly from a random distribution
y = np.random.randn(50)

plt.figure(figsize=(10, 6))
plt.scatter(x, y, s=100, alpha=0.6, edgecolors='white', linewidths=1.5)
plt.title('Scatter Plot Example', fontsize=16)
plt.xlabel('Feature 1', fontsize=12)
plt.ylabel('Feature 2', fontsize=12)
plt.grid(True, alpha=0.3)
plt.show()

# ML Example: Binary Classification Data
# Two classes with different colors

np.random.seed(42)

# Class 0 (centered around (-2, -2))
class_0_x = np.random.randn(50) - 2 # Notice how we shift the centre of the points by 2 to the left here
class_0_y = np.random.randn(50) - 2

# Class 1 (centered around (2, 2))
class_1_x = np.random.randn(50) + 2
class_1_y = np.random.randn(50) + 2

plt.figure(figsize=(10, 8))
plt.scatter(class_0_x, class_0_y, s=100, alpha=0.7,
            label='Class 0', c='red', edgecolors='white', linewidths=1.5)
plt.scatter(class_1_x, class_1_y, s=100, alpha=0.7,
            label='Class 1', c='blue', edgecolors='white', linewidths=1.5)
plt.title('Binary Classification Dataset', fontsize=16, fontweight='bold')
plt.xlabel('Feature 1', fontsize=12)
plt.ylabel('Feature 2', fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)
plt.axhline(y=0, color='white', linestyle='--', alpha=0.3)
plt.axvline(x=0, color='white', linestyle='--', alpha=0.3)
plt.show()

print("This is what classification data looks like!")
print("You'll work with this in Lectures 5-6 (Logistic Regression, Neural Networks)")

"""### Multiple Plots: Subplots

Show multiple visualizations side by side.

"""

# Create a 2x2 grid of plots
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: Sine wave .. again focus on the concept of subplots and
# don't worry about the functions (sine and cosine) used if this is new
x = np.linspace(0, 10, 100)
axes[0, 0].plot(x, np.sin(x), color='cyan')
axes[0, 0].set_title('Sine Wave')
axes[0, 0].grid(True, alpha=0.3)

# Plot 2: Cosine wave
axes[0, 1].plot(x, np.cos(x), color='magenta')
axes[0, 1].set_title('Cosine Wave')
axes[0, 1].grid(True, alpha=0.3)

# Plot 3: Exponential
axes[1, 0].plot(x, np.exp(-0.5*x), color='yellow')
axes[1, 0].set_title('Exponential Decay')
axes[1, 0].grid(True, alpha=0.3)

# Plot 4: Scatter
axes[1, 1].scatter(np.random.randn(50), np.random.randn(50),
                   c='green', alpha=0.6)
axes[1, 1].set_title('Random Scatter')
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("Subplots let you compare multiple visualizations!")

"""### ML Application: Comparing Training vs Validation Loss

"""

# Simulate training and validation loss
epochs = np.arange(1, 51)
train_loss = 2.0 * np.exp(-0.1 * epochs) + 0.1
val_loss = 2.0 * np.exp(-0.08 * epochs) + 0.15  # Slightly higher

plt.figure(figsize=(12, 7))
plt.plot(epochs, train_loss, linewidth=3, label='Training Loss',
         color='cyan', marker='o', markersize=4, markevery=5)
plt.plot(epochs, val_loss, linewidth=3, label='Validation Loss',
         color='orange', marker='s', markersize=4, markevery=5)
plt.title('Training vs Validation Loss', fontsize=18, fontweight='bold')
plt.xlabel('Epoch', fontsize=14)
plt.ylabel('Loss', fontsize=14)
plt.legend(fontsize=12, loc='upper right')
plt.grid(True, alpha=0.3)
plt.show()

print("This helps detect overfitting!")
print("If validation loss starts increasing while training loss decreases, → OVERFITTING")
print("Don't worry we will discuss this in Lectures 7-10")

"""### Histograms: Understanding Data Distribution

"""

# Generate data from normal distribution
np.random.seed(42)
data = np.random.randn(1000)

plt.figure(figsize=(10, 6))
plt.hist(data, bins=30, color='cyan', alpha=0.7, edgecolor='white')
plt.title('Feature Distribution (Normal)', fontsize=16, fontweight='bold')
plt.xlabel('Feature Value', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(True, alpha=0.3, axis='y')
plt.show()

print("Histograms show data distribution!")
print("Important in Lecture 7 (Data Preprocessing) to detect outliers and skewed data")

"""### Practice Time! 🎯

### Exercise 4.1: Create a Line Plot (2 points)

Plot a quadratic function: y = x²
"""

# Create x values from -5 to 5 with 100 points
# Calculate y = x²
# Create a plot with:
#   - Title: 'Quadratic Function' I want you to notice its shape because this is important
# when we talk about our cost function for linear regression, note that it has a global minima at x = 0.
#   - X label: 'x'
#   - Y label: 'y = x²'
#   - Grid enabled
#   - Figure size (10, 6)

# YOUR CODE HERE
raise NotImplementedError()

# Tests for Exercise 4.1
assert len(x) == 100, "x should have 100 points"
assert np.allclose(y, x**2), "y should be x squared"
assert x[0] == -5 and x[-1] == 5, "x range should be -5 to 5"
print("✓ Exercise 4.1 passed!")

"""### Exercise 4.2: Create a Scatter Plot (3 points)

Generate and visualize classification data.

"""

# Generate two classes of data:
# - Class A: 30 points, x centered at 1, y centered at 1
# - Class B: 30 points, x centered at 4, y centered at 4
# Plot them with different colors and a legend

np.random.seed(42)

# YOUR CODE HERE
raise NotImplementedError()

# Tests for Exercise 4.2
assert len(class_a_x) == 30, "Class A should have 30 points"
assert len(class_b_x) == 30, "Class B should have 30 points"
assert abs(np.mean(class_a_x) - 1) < 1, "Class A x should be centered near 1"
assert abs(np.mean(class_b_x) - 4) < 1, "Class B x should be centered near 4"
print("✓ Exercise 4.2 passed!")

"""### Exercise 4.3: Create Subplots (3 points)

Create a 2x2 grid showing different aspects of a dataset.

"""

# Given data
np.random.seed(42)
data = np.random.randn(100)
epochs = np.arange(1, 21)
loss = 1.0 * np.exp(-0.15 * epochs) + 0.05

# Create a 2x2 subplot grid:
# Top-left: Histogram of data
# Top-right: Line plot of loss vs epochs
# Bottom-left: Scatter plot (data[:-1] vs data[1:])
# Bottom-right: Box plot of data (to call boxplot: axes[1, 1].boxplot(data))

# YOUR CODE HERE
raise NotImplementedError()

# Tests for Exercise 4.3
assert len(data) == 100, "data should have 100 points"
assert len(epochs) == 20, "epochs should have 20 points"
assert len(loss) == 20, "loss should match epochs length"
print("✓ Exercise 4.3 passed!")

"""---

## Part 5: Object-Oriented Programming (OOP) for ML

OOP vs. Procedural Programming

### Why OOP Matters in ML

**Every ML model you'll implement uses classes!**

- **Lecture 3 (Linear Regression)**: `LinearRegression` class

- **Lecture 5 (Logistic Regression)**: `LogisticRegression` class

- **Lecture 6 (Neural Networks)**: `NeuralNetwork` class

- **Lecture 19-20 (CNNs)**: `ConvolutionalNetwork` class

**Classes let you organize code into reusable, modular components.**

### What is a Class?

A **class** is like a blueprint for creating objects. Think of it like:

- **Class** = Blueprint for a house

- **Object** = Actual house built from that blueprint

```
Class: LinearRegression
  - Attributes: weights, bias
  - Methods: fit(), predict(), score()

Object: model = LinearRegression()
  - model.fit(X, y)    ← Train the model
  - model.predict(X)   ← Make predictions
```

<div dir="rtl">

## الجزء ٥: البرمجة الشيئية (OOP) للتعلم الآلي

### لماذا OOP مهمة في التعلم الآلي؟

**كل نموذج تعلم آلي ستنفذه يستخدم الفئات (Classes)!**

- **المحاضرة ٣ (الانحدار الخطي)**: فئة <code>LinearRegression</code>
- **المحاضرة ٥ (الانحدار اللوجستي)**: فئة <code>LogisticRegression</code>
- **المحاضرة ٦ (الشبكات العصبية)**: فئة <code>NeuralNetwork</code>

</div>

## Understanding `__init__` (The Constructor)

### What is `__init__`?

`__init__` is a special method called a **constructor**. It automatically runs when you create a new object from a class.

Think of it like:
- When you buy a new phone, it comes with initial settings (language, timezone, etc.)
- `__init__` sets up the "initial settings" for your object

### Why "Constructor"?

It's called a constructor because it **constructs** (builds) the object by:
1. Setting up initial values
2. Allocating memory
3. Preparing the object for use

## Understanding `self`

### What is `self`?

`self` is a reference to the **current instance** of the class. It's how an object keeps track of its own data.

### Analogy: Your Personal Backpack

Imagine each object has its own backpack (`self`):
- When you say `self.features`, you're saying "MY features"
- Different objects have different backpacks with different contents

```python
# Two students, each with their own backpack
student1 = Student("Salma", 20)  # Salma's backpack
student2 = Student("Nader", 22)    # Nader's backpack

# self.name means "MY name"
# For student1, self.name = "Salma"
# For student2, self.name = "Nader"
```

### Simple Class Example
"""

# Define a simple class
class DataPoint:
    """Represents a single data point with features and label."""

    def __init__(self, features, label):
        """Initialize the data point."""
        self.features = features
        self.label = label

    def display(self):
        """Display the data point information."""
        print(f"Features: {self.features}")
        print(f"Label: {self.label}")


# Create objects (instances) of the class
point1 = DataPoint([1.5, 2.0, 3.0], 0) # notice how we passed [1.5, 2.0, 3.0] as one variable: features
point2 = DataPoint([4.0, 5.0, 6.0], 1)

print("Point 1:")
point1.display()
print("\nPoint 2:")
point2.display()

"""## Step-by-Step: What Happens When You Create an Object?

When you write: `point1 = DataPoint([1.5, 2.0, 3.0], 0)`

1. **Python creates a new empty object** (like getting a new empty backpack)

2. **Python calls `__init__`** with:
   - `self` = reference to this new object (point1)
   - `features` = [1.5, 2.0, 3.0]
   - `label` = 0

3. **Inside `__init__`:**
   - `self.features = features` → point1's features become [1.5, 2.0, 3.0]
   - `self.label = label` → point1's label becomes 0

4. **Object is ready to use!**

## Why Do We Need `self`?

Without `self`, all objects would share the same data:

```python
# BAD - Without self (this won't work properly!)
class BadDataPoint:
    def __init__(features, label):
        features = features  # Just creates local variables
        label = label        # These disappear after __init__ ends!
        # local means that these exist ONLY while __init__ is running
        # When __init__ ends, these variables are destroyed so they are not defined outside the function!

# GOOD - With self
class GoodDataPoint:
    def __init__(self, features, label):
        self.features = features  # Stores in the object .. attached to the object instance.
        self.label = label        # Data persists!
```

## Common Beginner Mistakes

### Mistake 1: Forgetting `self` in method definitions
```python
# WRONG
def display():  # Missing self!
    print(self.features)  # Error: self is not defined

# CORRECT
def display(self):
    print(self.features)
```

### Mistake 2: Forgetting `self` when accessing attributes
```python
# WRONG
def display(self):
    print(features)  # Error: features is not defined

# CORRECT
def display(self):
    print(self.features)  # Access THIS object's features
```

### Mistake 3: Confusing class variables with instance variables
```python
class DataPoint:
    # Class variable (shared by ALL objects)
    total_points = 0
    
    def __init__(self, features, label):
        # Instance variables (unique to EACH object)
        self.features = features
        self.label = label
        DataPoint.total_points += 1  # Increment shared counter
```

### ML Example: Simple Linear Model Class
"""

class SimpleLinearModel:
    """A simple linear model: y = w*x + b"""

    def __init__(self, weight=0.0, bias=0.0):
        """Initialize model with weight and bias."""
        self.weight = weight
        self.bias = bias

    def predict(self, x):
        """Make predictions: y = w*x + b"""
        return self.weight * x + self.bias

    def update_params(self, new_weight, new_bias):
        """Update model parameters."""
        self.weight = new_weight
        self.bias = new_bias
        print(f"Updated: weight={self.weight}, bias={self.bias}")


# Create a model
model = SimpleLinearModel(weight=2.0, bias=1.0)

# Make predictions
x_values = np.array([1, 2, 3, 4, 5])
predictions = model.predict(x_values) # argument

print(f"Model: y = {model.weight}*x + {model.bias}")
print(f"Inputs: {x_values}")
print(f"Predictions: {predictions}")

# Update parameters
model.update_params(3.0, 0.5)

"""### ML Example: Dataset Class

"""

class Dataset:
    """Manages features and labels for ML."""

    def __init__(self, X, y):
        """
        Initialize dataset.

        Args:
            X: Feature matrix (2D NumPy array)
            y: Labels (1D NumPy array)
        """
        self.X = X
        self.y = y

    def get_shape(self):
        """Return dataset dimensions."""
        return self.X.shape

    def get_sample(self, index):
        """Get a single sample."""
        return self.X[index], self.y[index]

    def normalize(self):
        """Normalize features using z-score."""
        mean = np.mean(self.X, axis=0)
        std = np.std(self.X, axis=0)
        self.X = (self.X - mean) / std
        print("Features normalized!")

    def summary(self):
        """Display dataset summary."""
        print(f"Samples: {self.X.shape[0]}")
        print(f"Features: {self.X.shape[1]}")
        print(f"Labels: min={np.min(self.y)}, max={np.max(self.y)}")


# Create dataset
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0, 0, 1, 1])

dataset = Dataset(X, y)
dataset.summary()
print()

# Get a sample
sample_x, sample_y = dataset.get_sample(0)
print(f"Sample 0: features={sample_x}, label={sample_y}")
print()

# Normalize
dataset.normalize()
print(f"Normalized X:\n{dataset.X}")

"""### ML Example: Metrics Calculator Class

"""

''' This example uses @staticmethod .. this is like defining the functions without
    a class but we just put 'Metrics' class to access it with dot for clarity that they
    belong to the same group or family of functions '''

class Metrics:
    """Calculate common ML metrics."""

    @staticmethod
    def mse(y_true, y_pred):
        """Mean Squared Error."""
        return np.mean((y_true - y_pred) ** 2)

    @staticmethod
    def mae(y_true, y_pred):
        """Mean Absolute Error."""
        return np.mean(np.abs(y_true - y_pred))

    @staticmethod
    def accuracy(y_true, y_pred):
        """Classification accuracy."""
        return np.mean(y_true == y_pred)

    @staticmethod
    def rmse(y_true, y_pred):
        """Root Mean Squared Error."""
        return np.sqrt(Metrics.mse(y_true, y_pred))


# Test the metrics
y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.1, 2.2, 2.9, 4.3, 4.8])

print(f"True values: {y_true}")
print(f"Predictions: {y_pred}")
print()
print(f"MSE: {Metrics.mse(y_true, y_pred):.4f}")
print(f"MAE: {Metrics.mae(y_true, y_pred):.4f}")
print(f"RMSE: {Metrics.rmse(y_true, y_pred):.4f}")
print()

# Classification example
y_true_class = np.array([0, 1, 1, 0, 1])
y_pred_class = np.array([0, 1, 0, 0, 1])
print(f"Classification Accuracy: {Metrics.accuracy(y_true_class, y_pred_class)*100:.1f}%")

"""### Inheritance (child and base/parent class) .. super
```python
class Autoencoder(nn.Module):
    '''
    A simple fully connected Autoencoder for 28x28 image reconstruction.

    The layers are defined explicitly to capture intermediate outputs for visualization.
    '''
    def __init__(self, input_size, latent_dim):
        super(Autoencoder, self).__init__()

        # Encoder Layers
        self.enc_layer1 = nn.Linear(input_size, 256)
        self.enc_relu1 = nn.ReLU()
        self.enc_layer2 = nn.Linear(256, latent_dim) # The bottleneck/latent representation

        # Decoder Layers
        self.dec_layer1 = nn.Linear(latent_dim, 256)
        self.dec_relu1 = nn.ReLU()
        self.dec_layer2 = nn.Linear(256, input_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # Flatten the input image (Batch x 784)
        # Flatten the 28 x 28 image into a 784 element vector. It treats each of the 784 pixels as an independent feature.
        batch_size = x.size(0)
        x_flat = x.view(batch_size, -1)

        ... rest of code ...
```

### Practice Time! 🎯

### Exercise 5.1: Create a DataPoint Class (3 points)
"""

# Create a class called 'Point2D' that:
# - Takes x and y coordinates in __init__
# - Has a method distance_from_origin() that returns sqrt(x² + y²)
# - Has a method display() that prints the coordinates

# YOUR CODE HERE
raise NotImplementedError()


# Test
p = Point2D(3, 4)
p.display()
print(f"Distance from origin: {p.distance_from_origin():.2f}")

# Tests for Exercise 5.1
p1 = Point2D(3, 4)
assert p1.x == 3 and p1.y == 4, "Coordinates incorrect"
assert abs(p1.distance_from_origin() - 5.0) < 0.01, "Distance calculation incorrect"

p2 = Point2D(0, 0)
assert abs(p2.distance_from_origin() - 0.0) < 0.01, "Origin distance should be 0"
print("✓ Exercise 5.1 passed!")

"""### Exercise 5.2: Create a Linear Model Class (4 points)

"""

# Create a class 'LinearModel' that:
# - Initializes with weights (NumPy array) and bias (float)
# - Has a predict(X) method: returns X @ weights + bias
# - Has a calculate_loss(X, y) method: returns MSE between predictions and y

# YOUR CODE HERE
raise NotImplementedError()


# Test
X_test = np.array([[1, 2], [2, 3], [3, 4]])
y_test = np.array([5, 8, 11])
weights_test = np.array([1.0, 2.0])
bias_test = 0.0

model = LinearModel(weights_test, bias_test)
preds = model.predict(X_test)
loss = model.calculate_loss(X_test, y_test)

print(f"Predictions: {preds}")
print(f"Loss: {loss:.4f}")

# Tests for Exercise 5.2
X = np.array([[1, 2], [2, 3]])
y = np.array([5, 8])
w = np.array([1.0, 2.0])
b = 0.0

m = LinearModel(w, b)
pred = m.predict(X)
assert np.allclose(pred, np.array([5, 8])), "Predictions incorrect"

loss_val = m.calculate_loss(X, y)
assert abs(loss_val - 0.0) < 0.01, "Loss should be 0 for perfect predictions"

print("✓ Exercise 5.2 passed!")

"""---

## Part 6: Final Comprehensive Exercise

### Putting It All Together!

Now you'll combine **everything** you learned to directly link that to the upcoming Machine learning models:

✅ NumPy arrays

✅ Vectorization

✅ Broadcasting

✅ Statistical operations

✅ Matplotlib visualization

✅ Object-Oriented Programming

**Task**: Build a complete mini Machine learning pipeline!

<div dir="rtl">

## الجزء ٦: التمرين الشامل النهائي

### يلا نجمع الكلام في مثال يمهد بشكل مباشر لل Machine Learning

✅ مصفوفات NumPy

✅ التوجيه الشعاعي

✅ Broadcasting

✅ العمليات الإحصائية

✅ التصور البياني باستخدام Matplotlib

✅ البرمجة الشيئية

**المهمة**: بناء Pipeline تعلم آلي صغير كامل!

</div>

### Final Example: Complete ML Pipeline (10 points)

Create a classification pipeline with:

1. Synthetic 2D data generation (2 classes)

2. Feature normalization (z-score)

3. Simple model class

4. Predictions and error calculation

5. Comprehensive visualization (2x2 subplots)
"""

# YOUR CODE HERE
raise NotImplementedError()

"""---

## Congratulations! 🎉

You've completed Week 2!

### What You Learned:

✅ **Part 1: NumPy Arrays** - Creating, indexing, slicing, shapes

✅ **Part 2: Vectorization** - Fast operations, broadcasting

✅ **Part 3: Statistics** - Mean, std, normalization techniques

✅ **Part 4: Matplotlib** - Line plots, scatter plots, subplots, histograms

✅ **Part 5: OOP** - Classes, methods, ML model structures

✅ **Part 6: Integration** - Complete ML pipeline

### Skills Acquired:

- Manipulate multi-dimensional data with NumPy

- Write efficient vectorized code

- Normalize and preprocess data

- Create informative visualizations

- Build ML models using classes

- Combine all tools into a working pipeline

### What's Next (Week 3):

**Lecture 3: Linear Regression** - Your first REAL ML algorithm!

You'll implement:

- Net input function

- Cost function

- Gradient descent optimization

- Model evaluation and visualization

**Everything you learned this week will be used!**


### Submission:

1. Save this notebook

2. Verify all ✓ marks appear

3. Send an email to Dr. Mahmoud if you have any questions

**See you in Week 3!** 🚀

<div dir="rtl">

# مبروك! 🎉
"""